name: ROS 2 TimePublisher Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: ros-tooling/setup-ros-action@v0.1

    - name: Set up ROS 2 environment
      run: |
        sudo apt update && sudo apt install -y curl gnupg lsb-release
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] https://packages.ros.org/ros2/ubuntu $(lsb_release -c | awk "{print $2}") main" > /etc/apt/sources.list.d/ros2.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop
        sudo apt install -y python3-colcon-common-extensions

    - name: Set up workspace
      run: |
        mkdir -p ~/ros2_times_ws/src
        cd ~/ros2_times_ws/src
        git clone https://github.com/yourusername/ros2_times_ws.git
        cd ~/ros2_times_ws
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro humble -y

    - name: Build the workspace
      run: |
        cd ~/ros2_times_ws
        colcon build --symlink-install

    - name: Source the setup script
      run: |
        source ~/ros2_times_ws/install/setup.bash

    - name: Run test
      run: |
        chmod +x test.bash
        ./test.bash

